version: '3.5'

services:
  marketing:
    container_name: 'micro-marketing'
    image: node:16
    restart: always
    working_dir: /app
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://mongo:27017/micro-marketing
    volumes:
      - ./dist/:/app/dist/
      - ./package.json:/app/package.json
    command: bash -c "npm install --omit=dev --force && npm run start"
    depends_on:
      - mongo
      - mongo-express
  mongo:
    container_name: 'micro-mongo'
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  mongo-express:
    container_name: 'micro-mongo-express'
    image: "mongo-express"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 12345678
      ME_CONFIG_MONGODB_URL: mongodb://root:12345678@mongo:27017/
networks:
  default:
    name: local
